# Generated by Django 4.2.7 on 2023-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('read_status', models.BooleanField(default=False)),
                ('redirect_url', models.CharField(max_length=100)),
            ],
        ),
    ]
