# Generated by Django 4.2.7 on 2023-11-13 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('caretaker', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('listed', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('L', 'listed'), ('W', 'withdrawn'), ('A', 'adopted')], max_length=10)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=50)),
                ('description', models.CharField(max_length=600)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'approved'), ('P', 'pending'), ('D', 'denied')], max_length=50)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seeker')),
            ],
        ),
    ]
