# Generated by Django 4.2.7 on 2023-11-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('caretaker', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('listed', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('L', 'listed'), ('W', 'withdrawn'), ('A', 'adopted')], max_length=10)),
            ],
        ),
    ]
