# Generated by Django 4.2.6 on 2023-11-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
