# Generated by Django 4.2.7 on 2023-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seeker_profile/'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='shelter_image',
            field=models.ImageField(blank=True, null=True, upload_to='shelter_profile/'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='shelter_name',
            field=models.CharField(default='sheltergang', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seeker',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
