# Generated by Django 4.2.6 on 2023-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_seeker_phone_number_alter_shelter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='shelter_name',
            field=models.CharField(default='sheltergang', max_length=128),
            preserve_default=False,
        ),
    ]
